package com.smsanalytic.lotto.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountObjectDaoConfig;
    private final DaoConfig debtObjectDaoConfig;
    private final DaoConfig lotoNumberObjectDaoConfig;
    private final DaoConfig smsObjectDaoConfig;
    private final DaoConfig xSMBObjectDaoConfig;

    private final AccountObjectDao accountObjectDao;
    private final DebtObjectDao debtObjectDao;
    private final LotoNumberObjectDao lotoNumberObjectDao;
    private final SmsObjectDao smsObjectDao;
    private final XSMBObjectDao xSMBObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountObjectDaoConfig = daoConfigMap.get(AccountObjectDao.class).clone();
        accountObjectDaoConfig.initIdentityScope(type);

        debtObjectDaoConfig = daoConfigMap.get(DebtObjectDao.class).clone();
        debtObjectDaoConfig.initIdentityScope(type);

        lotoNumberObjectDaoConfig = daoConfigMap.get(LotoNumberObjectDao.class).clone();
        lotoNumberObjectDaoConfig.initIdentityScope(type);

        smsObjectDaoConfig = daoConfigMap.get(SmsObjectDao.class).clone();
        smsObjectDaoConfig.initIdentityScope(type);

        xSMBObjectDaoConfig = daoConfigMap.get(XSMBObjectDao.class).clone();
        xSMBObjectDaoConfig.initIdentityScope(type);

        accountObjectDao = new AccountObjectDao(accountObjectDaoConfig, this);
        debtObjectDao = new DebtObjectDao(debtObjectDaoConfig, this);
        lotoNumberObjectDao = new LotoNumberObjectDao(lotoNumberObjectDaoConfig, this);
        smsObjectDao = new SmsObjectDao(smsObjectDaoConfig, this);
        xSMBObjectDao = new XSMBObjectDao(xSMBObjectDaoConfig, this);

        registerDao(AccountObject.class, accountObjectDao);
        registerDao(DebtObject.class, debtObjectDao);
        registerDao(LotoNumberObject.class, lotoNumberObjectDao);
        registerDao(SmsObject.class, smsObjectDao);
        registerDao(XSMBObject.class, xSMBObjectDao);
    }
    
    public void clear() {
        accountObjectDaoConfig.clearIdentityScope();
        debtObjectDaoConfig.clearIdentityScope();
        lotoNumberObjectDaoConfig.clearIdentityScope();
        smsObjectDaoConfig.clearIdentityScope();
        xSMBObjectDaoConfig.clearIdentityScope();
    }

    public AccountObjectDao getAccountObjectDao() {
        return accountObjectDao;
    }

    public DebtObjectDao getDebtObjectDao() {
        return debtObjectDao;
    }

    public LotoNumberObjectDao getLotoNumberObjectDao() {
        return lotoNumberObjectDao;
    }

    public SmsObjectDao getSmsObjectDao() {
        return smsObjectDao;
    }

    public XSMBObjectDao getXSMBObjectDao() {
        return xSMBObjectDao;
    }

}
